# on a given raw file, get all the N-2 HV line outage combos possible
# test these combos on a power flow and see which ones do not lead to any topology inconsistencies
# List these cases out, so that we can do some TS on these
import getOKN_2.py # please note, this needs PSSE to run

# output a list of all the events to be simulated to a text file, from the double branch outage cases
import listN_2Sim



########## 
### PSSE simulation scripts

# save the raw and dyr file as .sav and .snp  files
import PSSESavSnap

# script to visualize the transient signals (voltage/angle/frequency)
# has an interactive dialogue which asks for the event, type of variable, transient or steady
# loops till the shell is closed
import visualizeOAT

# generate the python scripts to generate chunks of  simulations (PSSE or TS3ph)
import generateSimBatches


# here you need to run the batch file generated by generatePSSESimBatches
# run all the batch scripts
#import runAllBatches

#####


###########
### TS3ph simulation scripts

# run getOKN_2.py and listN_2Sim.py
# then run generateSimBatches with the PSSE simulation part commented. 
# also make sure that the sample TS3ph simulation file is provided as input